name: recipe_book_flutter
description: All recipes in one place
publish_to: 'none'
version: 1.1.0+2
environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  beamer: 0.14.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.0.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  json_annotation: ^4.8.0
  provider: ^6.0.5
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.3
  carapacik_lints: ^1.3.1
  json_serializable: ^6.6.1
  swagger_parser: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/icons/
    - assets/images/
