name: recipebook
description: All recipes in one place
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  beamer: ^0.14.1 # навигация
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0 # взаимодействие с API
  dotted_border: ^2.0.0+1
  file_picker: ^4.0.0
  fish_redux: ^0.3.7
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  json_annotation: ^4.0.1
  provider: ^6.0.0
  url_launcher: ^6.0.9 # запуск внешних ссылок
  url_strategy: ^0.2.0 # убирает '#' в url

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^4.1.4
  lint: ^1.6.0

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/icons/
    - assets/images/
